version: '3.8'

services:
  dataBase:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    container_name: trip-api
    ports:
      - '3000:3000'
    depends_on:
      - dataBase
    environment:
      - MONGO_URI=${MONGO_URI}
volumes:
  mongo-data: